conditiona_tool_implementation
hertz-ai/HARTOS pull request #16
Opened 2024-02-27 13:06 UTC by SahilHeartzai

2024-02-27 15:37 UTC, lawlietlight requested changes

2024-02-27 15:37 UTC, lawlietlight commented on langchain.log
> +2024-02-24 18:31:57,445 - langchain_gpt_api- [RequestID: 10000000001] - INFO - before: memory object is not none and metadata is {'request_Id': 10000000001}, False
Please remove non code files which are generated

2024-02-27 15:37 UTC, lawlietlight commented on langchain_gpt_api.py
> +        'google_search': '''Search Google for recent results and retrieve URLs that are suitable for web crawling. Ensure that the search responses include the source URL from which the data was extr
Can't we define this at class level only once and extract and use in both places

2024-02-29 19:04 UTC, SahilHeartzai commented on langchain.log
> +2024-02-24 18:31:57,445 - langchain_gpt_api- [RequestID: 10000000001] - INFO - before: memory object is not none and metadata is {'request_Id': 10000000001}, False
done

2024-02-29 19:04 UTC, SahilHeartzai commented on langchain_gpt_api.py
> +        'google_search': '''Search Google for recent results and retrieve URLs that are suitable for web crawling. Ensure that the search responses include the source URL from which the data was extr
done

2024-03-01 07:24 UTC, lawlietlight requested changes

2024-03-01 07:24 UTC, lawlietlight commented on req.txt
how many requirements.txt file exists? why is this file name in non standard format?

2024-03-14 17:43 UTC, lawlietlight commented on req.txt
is this addressed?

2024-03-14 17:45 UTC, merged